version: '3.3'

services:
  bot:
    tty: true
    build: './'
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/wzstats?schema=public
  postgres:
    image: 'postgres:alpine'
    volumes:
      - wzstats_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  wzstats_postgres_data:
